### ISSUE TITLE
单目+IMU+轮式里程计

### ISSUE THREAD

**Issue by eejacky** [TouchDeeper/VIW-Fusion#10]
good job！
有两个问题请教下：
1.单目+IMU+轮式里程计 是否需要良好的初始化？
2.轮式里程计ROS消息的时间戳需要和IMU以及单目对齐吗？

**Comment by TouchDeeper** [comment]
1. 单目+IMU需要良好的初始化，轮速可以增强初始化的鲁棒性和精度
2. 时间戳是否需要对齐主要取决与是否已经时间同步，不确定的话可以分别测试下开启和关闭时延标定的效果

**Comment by eejacky** [comment]
谢谢！
昨天用我自己的小车（有轮速信息）和D435i（单目+IMU）测试了，发现偏差比较大
1.视频当中，你小车的 odom 话题频率是多少？
2.还没有细看代码，在轮子打滑的情况下，代码有做处理吗？

**Comment by TouchDeeper** [comment]
1. odom话题频率可以用ROS打印出来看下，没记错应该是50HZ
2. 在测试的场景，打滑不会特别大，所以没有特别处理。你可以看下这篇论文Robust Odometry using Sensor Consensus Analysis，有部分传感器一致性检验的内容
