### ISSUE TITLE
轮速里程计平面约束

### ISSUE THREAD

**Issue by dean1314** [TouchDeeper/VIW-Fusion#11]
请问下作者有没有测试过上下坡情况，貌似平面约束对上下坡场景不好

**Comment by TouchDeeper** [comment]
目前的模型和代码不支持平面变化很大的场景，但改起来也不难，首先识别出平面产生变化，然后再新建平面模型

**Comment by dean1314** [comment]
好的，谢啦，如果把平面约束改成vins on wheel论文中的第二种随机模型，不知道作者有没有测试过呢

**Comment by TouchDeeper** [comment]
这里使用的就是第二种模型哈，一般不使用确定性约束，除非是该约束精确成立，如恒等式

**Comment by dean1314** [comment]
好的，谢谢，我看你yaml配置里面配有kaist39文件，请问这边有用kaist39数据集测试过嘛？

**Comment by TouchDeeper** [comment]
跑kaist数据集还有些问题没空解

**Comment by qiaozhijian** [comment]
@TouchDeeper 看论文里大部分是认为轮速记坐标系始终处于平面上，虽然地面机器人有地面接触约束，这种假设是合理的，但一般多传感融合系统（本文也是）都是以IMU为参考，把位姿都统一到IMU坐标系下的，因此在车辆行驶平稳，IMU和轮速记外参不变的情况下，能否把假设改为认为IMU坐标系始终在平面上呢？

**Comment by TouchDeeper** [comment]
@qiaozhijian 嗯嗯，也是可以的，不过优势在哪呢

**Comment by qiaozhijian** [comment]
> @qiaozhijian 嗯嗯，也是可以的，不过优势在哪呢

嘿嘿，可能只是公式更简洁一点。我太能确定残差里又多了一个优化变量（IMU和里程计外参）会造成怎样的影响。
