### ISSUE TITLE
Question about download dataset_viwo datasets from google cloud storage

### ISSUE THREAD

**Issue by Jaxon2018** [TouchDeeper/VIW-Fusion#12]
I can't download the ridgeback_light.bag and ridgeback_dark.bag from google cloud storage "https://drive.google.com/drive/folders/1m2msbo3DRGhtINtDE47v-1blyJc0RK0E",  "web error" or "download is forbidden" information is usually hinted and the download is stopped, so would you like to share the datasets in baidu cloud storage or other link which can be download easily for us? Thank you very much.

**Comment by TouchDeeper** [comment]
you can try:
link：https://pan.baidu.com/s/1Zk9ZkvpXftwWagPkEwpy-A
pwd：viwo
