### ISSUE TITLE
Relate Paper

### ISSUE THREAD

**Issue by chengwei0427** [TouchDeeper/VIW-Fusion#13]
Hi， @TouchDeeper 

Thanks for your great work. 

Is there any relate Paper or blog about this project?

**Comment by TouchDeeper** [comment]
Hi, @chengwei0427  

This project and the formula behind the code are derived by myself, there is not a paper or blog about this project. When the thesis or the related paper is published, I will push it to this repositry as soon as possible.

**Comment by chengwei0427** [comment]
Hi, @TouchDeeper 

Thanks for your reply.

Can you give me some information about the odometer motion model, about  Covariance and Jacobian derivation in wheel integration?

**Comment by chengwei0427** [comment]
Hi, @TouchDeeper 

Any new progress about the reference material?

I have send you an email `《VIW-Fusion中融合轮速计相关问题请教》` ,hope to get your reply.

**Comment by TouchDeeper** [comment]
@chengwei0427 你好，我之前可能太忙了，给漏了这封邮件，后续我尽量抽空回答。另外论文已经上传，应该可以解你的部分问题。

**Comment by chengwei0427** [comment]
Hi, @TouchDeeper 

     Thank you for your reply.
