### ISSUE TITLE
请问在初始化的时候没有对轮速计的内外参进行初始化吗？而是直接给的初值吗？

### ISSUE THREAD

**Issue by RobotYi1** [TouchDeeper/VIW-Fusion#17]

**Comment by TouchDeeper** [comment]
进行了初始化，和初始化陀螺仪bias的方式类似

**Comment by RobotYi1** [comment]
但是我在代码里没有找到关于轮速计的内外参的初始化相关内容，你能给我说下代码中具体位置吗。
bool VisualIMUAlignment(map<double, ImageFrame> &all_image_frame, Vector3d* Bgs, Vector3d &g, VectorXd &x)
{
    solveGyroscopeBias(all_image_frame, Bgs);
    if(USE_WHEEL)
        return LinearAlignmentWithWheel(all_image_frame, g, x);
    else
        return LinearAlignment(all_image_frame, g, x);

}
这一段是陀螺仪bias初始化的地方，没有轮速计的。

**Comment by TouchDeeper** [comment]
@cheyifanp 这里是直接用1初始化了
