### ISSUE TITLE
关于Z方向上的漂移有点疑问想请教一下

### ISSUE THREAD

**Issue by zxh2015** [TouchDeeper/VIW-Fusion#18]
之前有用vins fusion的单目+imu跑过很多数据，Z方向大致是可以收敛的，但是引入了轮速之后发现Z方向的漂移经常会比vins fusion高，不加平面约束的时候不是很理想，不太清楚这个误差是共有的特性还是自己在标定参数时引入的

**Comment by TouchDeeper** [comment]
引入轮速发现Z方向漂移的现象我没怎么发现，或许是你跑的数据集里轮速打滑的情况比较多。
另外轮速的内外参可以考虑需要在线标定。

**Comment by zxh2015** [comment]
> 引入轮速发现Z方向漂移的现象我没怎么发现，或许是你跑的数据集里轮速打滑的情况比较多。 另外轮速的内外参可以考虑需要在线标定。

感谢回复,外参在线标定确实表现会比较好的,本身外参的影响是比较大的,但是这个也不是很能解释Z漂移,可能确实我的数据震荡和打滑情况比较多,还需要考虑一下

**Comment by RobotYi1** [comment]
请问，在跑kaist数据集时候，有遇到Z方向飘移很大的情况吗，怎么解决的呢

**Comment by TouchDeeper** [comment]
@cheyifanp  可以用一下零速修正

**Comment by RobotYi1** [comment]
@TouchDeeper 请问零速校正要怎么加呢，我的做法是利用轮速计进行零速检测，检测到时把零速约束加入到优化项中了，同时把视觉约束的方差设置为零，结果是当处于静止状态时，轨迹会漂移然后崩掉。像问下我的思路是对的吗
