### ISSUE TITLE
关于添加ZUPT约束的一点疑问

### ISSUE THREAD

**Issue by RobotYi1** [TouchDeeper/VIW-Fusion#19]
请问零速校正要怎么加呢，我的做法是利用轮速计进行零速检测，检测到时，把零速约束加入到优化项中了，同时把视觉约束的方差设置为零，结果是当处于静止状态时，轨迹会漂移然后崩掉。想问下问下我的思路是对的吗？
零速约束是：当前时刻的速度为零。当前时刻与上一时刻的相对位置为零， 当前时刻与上一时刻的相对旋转为单位阵

**Comment by TouchDeeper** [comment]
视觉约束方差不能设置为0，有两个问题：
1. 按照你的修改思路，方差应该要变大，当然也可以不变，但不应该是变小
2. 方差为0，计算的信息矩阵会有数值问题
