### ISSUE TITLE
ros-noetic and ros2 version

### ISSUE THREAD

**Issue by yxianzhe** [TouchDeeper/VIW-Fusion#22]
我改了ros-noetic和ros2的版本，都已经调试完成。
其中，noetic版本用rideback_dark完成了测试，vins_estimator和loop_fusion节点都没有问题。ros2版本是在ubuntu22.04 ros-humble下调试的，由于一些原因，rideback这两个包没能转成ros2 bag的格式，所以我只测试了Euroc数据集，vins_estimator和loop_fusion节点也都没有问题。代码我上传在自己的仓库了，可以看一下[noetic](https://github.com/yxianzhe/VIW-Fusion/tree/noetic)和[ros2-humble](https://github.com/yxianzhe/VIW-Fusion/tree/VIW-Fusion-ROS2)。在纯净的系统上安装好sophus和ceres之后，应该是很容易编译的。
请问您可以新开两个分支noetic和ros2-humble让我提交pr吗？

**Comment by julyfire-wang** [comment]
你好！ 我用自己录的数据跑的时候，会报以下初始化错误，请问您是否知道原因？
[ WARN] [1690423697.385804257]: gyroscope bias initial calibration -nan -nan -nan
Sophus ensure failed in function 'void Sophus::SO3Base<Derived>::normalize() [with Derived = Sophus::SO3<double>]', file '/home/nhy/study/slambook2/3rdparty/Sophus/sophus/so3.hpp', line 320.
Quaternion (-nan  nan -nan -nan) should not be close to zero!

**Comment by TouchDeeper** [comment]
没问题，README最好写一下安装过程哈，分支已经创建好了
