### ISSUE TITLE
gyroscope bias initial calibration -nan -nan -nan【陀螺仪初始化问题】

### ISSUE THREAD

**Issue by julyfire-wang** [TouchDeeper/VIW-Fusion#23]
我用自己录的数据跑的时候遇到以下问题，请问您是否知道原因。
[ WARN] [1690423697.385804257]: gyroscope bias initial calibration -nan -nan -nan
Sophus ensure failed in function 'void Sophus::SO3Base<Derived>::normalize() [with Derived = Sophus::SO3<double>]', file '/home/nhy/study/slambook2/3rdparty/Sophus/sophus/so3.hpp', line 320.
Quaternion (-nan  nan -nan -nan) should not be close to zero!
已放弃 (核心已转储)

**Comment by TouchDeeper** [comment]
那需要看一下是否录到了陀螺仪数据，你可以播放bag，并用rostopic看一下值
