### ISSUE TITLE
Plane Constraint Problem on OpenLORIS dataset

### ISSUE THREAD

**Issue by yxianzhe** [TouchDeeper/VIW-Fusion#24]
我在OpenLORIS数据集上测试了您的算法，发现关闭和开启平面约束前后，效果差很大。关闭平面约束时，轨迹正常，开启后直接跑飞了，如图是在office1_5数据集上的开启平面约束前后的结果：
![Screenshot from 2023-07-27 17-47-37](https://github.com/TouchDeeper/VIW-Fusion/assets/75716845/a768de34-7cfc-4920-84fb-887b045b901c)
![Screenshot from 2023-07-27 17-49-20](https://github.com/TouchDeeper/VIW-Fusion/assets/75716845/d516259c-aa46-4da5-ab2a-c67245b9288b)
在office的其他sequence上以及cafe数据上也是相同的结果，开启平面约束后都跑飞了。
我想请教一下是不是有哪个参数我没有配置好？

**Comment by yxianzhe** [comment]
在其中一个数据上没有跑飞，猜测其他数据上跑飞的原因可能是平面的初始化结果不太理想

**Comment by zhh2005757** [comment]
想问下OpenLORIS数据集中IMU和轮速的外参从哪里获取呢？

**Comment by yxianzhe** [comment]
> 想问下OpenLORIS数据集中IMU和轮速的外参从哪里获取呢？

数据集的github上有个.py文件里面有[openloris_tf_data.py](https://github.com/lifelong-robotic-vision/openloris-scene-tools/blob/master/benchmark/openloris_tf_data.py)

**Comment by zhh2005757** [comment]
感谢大佬！

**Comment by yxianzhe** [comment]
> 我在OpenLORIS数据集上测试了您的算法，发现关闭和开启平面约束前后，效果差很大。关闭平面约束时，轨迹正常，开启后直接跑飞了，如图是在office1_5数据集上的开启平面约束前后的结果： ![Screenshot from 2023-07-27 17-47-37](https://user-images.githubusercontent.com/75716845/256500390-a768de34-7cfc-4920-84fb-887b045b901c.png) ![Screenshot from 2023-07-27 17-49-20](https://user-images.githubusercontent.com/75716845/256500211-d516259c-aa46-4da5-ab2a-c67245b9288b.png) 在office的其他sequence上以及cafe数据上也是相同的结果，开启平面约束后都跑飞了。 我想请教一下是不是有哪个参数我没有配置好？

您好，这个问题似乎是因为代码中有个小bug，在estimator.cpp的vector2double中，原本应该是q2的地方错写成了q，改正之后平面约束可以正常运行了。
![Screenshot from 2023-08-03 16-38-33](https://github.com/TouchDeeper/VIW-Fusion/assets/75716845/8058189b-7845-4328-94f6-d8a31418a096)
![Screenshot from 2023-08-03 16-37-35](https://github.com/TouchDeeper/VIW-Fusion/assets/75716845/a6381383-6e63-4a70-ab23-1c8a158a9826)

**Comment by zhh2005757** [comment]
平面约束开启前后差别大吗

**Comment by yxianzhe** [comment]
> 平面约束开启前后差别大吗

还没做定量对比，直观来看运行结果的话对z轴的漂移确实有抑制作用
