### ISSUE TITLE
undefined reference to std::locale fmt

### ISSUE THREAD

**Issue by wzhxp** [TouchDeeper/VIW-Fusion#27]
/usr/bin/ld: libhelloslam.so: undefined reference to std::locale fmt::v8::detail::locale_ref::get<std::locale>() const' /usr/bin/ld: libhelloslam.so: undefined reference to fmt::v8::detail::assert_fail(char const*, int, char const*)'
/usr/bin/ld: libhelloslam.so: undefined reference to fmt::v8::detail::error_handler::on_error(char const*)' /usr/bin/ld: libhelloslam.so: undefined reference to fmt::v8::vprint(fmt::v8::basic_string_view, fmt::v8::basic_format_args<fmt::v8::basic_format_context<fmt::v8::appender, char> >)'
/usr/bin/ld: libhelloslam.so: undefined reference to `fmt::v8::detail::throw_format_error(char const*)'

**Comment by wzhxp** [comment]
https://blog.csdn.net/m0_53271135/article/details/131115002

**Comment by wzhxp** [comment]
https://blog.csdn.net/m0_53271135/article/details/131115002

**Comment by TouchDeeper** [comment]
解决了吗，应该是版本问题，sophus安装可以参考[这里](https://github.com/TouchDeeper/VIW-Fusion?tab=readme-ov-file#13-sophus)
