### ISSUE TITLE
ground_truth

### ISSUE THREAD

**Issue by JDYS12138** [TouchDeeper/VIW-Fusion#28]
Does the dataset provided by the author contain real trajectories?

**Comment by srividyaprasad** [comment]
No messages in /vins_estimator/groundtruth topic.
Requesting the author to provide a dataset with Lidar ground truth.

**Comment by TouchDeeper** [comment]
@JDYS12138 @srividyaprasad This dataset does not have ground truth. You can use the distance between the start and end points as the ground truth, or use the trajectory after loop closure as the ground truth. Alternatively, you can use some datasets that include wheel speed and have ground truth, such as openloris-scene.

**Comment by srividyaprasad** [comment]
Great, thanks a lot. Will try these routes.

How have you achieved your error results and how can I recreate your
results? To benchmark this against VINS-Fusion and other VIO repos.

**Comment by TouchDeeper** [comment]
@srividyaprasad there is start-end error result in my thesis paper, you can refer to the data in Table 5-1 and Table 5-2.

**Comment by srividyaprasad** [comment]
Thank you

**Comment by srividyaprasad** [comment]
https://github.com/TouchDeeper/VIW-Fusion/blob/master/config/OpenORIS/realsense_stereo_imu_config.yaml
Are these OpenLORIS extrinsic and intrinsic parameters configured and run by you?
