### ISSUE TITLE
使用EuRoC数据集的配置参数会报错

### ISSUE THREAD

**Issue by Zeqing0213** [TouchDeeper/VIW-Fusion#29]
rosrun vins viwo_node ~/catkin_ws/src/VIW-Fusion/config/euroc/euroc_stereo_config.yaml 运行节点之后报错
`[WARN] [1722600706.279088038] [Main]: waiting for image and imu...
terminate called after throwing an instance of 'rclcpp::exceptions::InvalidTopicNameError'
  what():  Invalid topic name: topic name must not be empty string:
  ''
   ^
`
使用realsense_stereo_imu_config_ridgeback.yaml参数就不会报这个错误

**Comment by TouchDeeper** [comment]
euroc数据集没有轮速消息，euroc的配置文件少了一些我加的配置，问题可能出在这里

**Comment by Zeqing0213** [comment]
收到，感谢
