### ISSUE TITLE
Ubuntu20.04 ros noetic support

### ISSUE THREAD

**Issue by gongyue666** [TouchDeeper/VIW-Fusion#3]
Hi I build it under ubuntu 20.04, get many errors, any update?

**Comment by gongyue666** [comment]
version of fmt and Sophus, the master branch of these github have been updated. What's the version should use?

**Comment by TouchDeeper** [comment]
Hi, you can paste the errors here. 
I have not tested on ubuntu20.04. You can try on 18.04. 
If I am available, I will try to compile it on ubuntu20.04.
For Sophus, I think you can use the latest code.

**Comment by gongyue666** [comment]
I finally sloved all the problem, using fmt 7.X and latest Sophus. With opencv 4.0 there should change some lines to adopt. Ceres version is 1.7.x, which 2.0 is not ok.

**Comment by gongyue666** [comment]
I run it with my own robot also D435i，but result is not very good as your bag. any advice?

**Comment by TouchDeeper** [comment]
> I finally sloved all the problem, using fmt 7.X and latest Sophus. With opencv 4.0 there should change some lines to adopt. Ceres version is 1.7.x, which 2.0 is not ok.

Nice， you can create a pull request

**Comment by TouchDeeper** [comment]
> I run it with my own robot also D435i，but result is not very good as your bag. any advice?

I think you need to check something：
1. Calibrate your D435i device.
2. Modify the config file according to the calibration result. The default imu in my example config is the one equipped in ridgeback. The imu in D435i also works, but you need to modify the extrinsic between camera and imu in the config file.
