### ISSUE TITLE
wait for wheel ... 

### ISSUE THREAD

**Issue by Zeqing0213** [TouchDeeper/VIW-Fusion#31]
使用openloris数据集进行测试，启动节点后并且播放rosbag，节点一直显示wait for wheel ... 
在rviz上查看/odom相关话题时会显示：
`[rviz2-1] [INFO] [1722865709.442545945] [rviz2]: Message Filter dropping message: frame 'base_odom' at time 1560025198.132 for reason 'discarding message because the queue is full'
` 这个问题会出在哪里呢？ 使用ros2 topic echo是可以看到odom话题的数据的

**Comment by TouchDeeper** [comment]
看提示是message queue满了导致丢弃了，你可以加一些log看下具体是什么情况

**Comment by Zeqing0213** [comment]
一开始我利用rviz订阅odom话题，正如报错显示`Message Filter dropping message: frame 'base_odom' at time 1560025198.132 for reason 'discarding message because the queue is full'  `随后我认为是tf变换出现了问题，数据集包含的tf_static话题echo不出来东西，于是我自己添加了tf变换之后仍旧显示“wait for wheel “，似乎里程计的信息没有传递给viw_estimator节点。
最后我重新自己写了一个odom节点，包括动态的tf变换，可以成功跑通节点，很奇怪的问题。

**Comment by TouchDeeper** [comment]
ok，rviz的话确实需要配置好坐标系
