### ISSUE TITLE
IMU和轮速计外参标定

### ISSUE THREAD

**Issue by Zeqing0213** [TouchDeeper/VIW-Fusion#32]
想实机部署一下这个算法，发现IMU和轮速需要联合标定，这个外参是通过什么工具或者软件包获取的呢？假如`estimate_wheel_extrinsic`这个参数的值设置成2（不知道外参），效果会比使用默认的参数好吗？

**Comment by TouchDeeper** [comment]
设置成2的话对于标定运动有要求，需要走8字。可以通过测量或者大概估算一个初始值，用1模式去优化这个初始外参

**Comment by Zeqing0213** [comment]
好的好的，非常感谢！自己也刚接触到这个领域还不是通透，请问一下这个具体是如何测量或者估算的呢？imu和cam的标定我看有一些工具包就可以完成了

**Comment by TouchDeeper** [comment]
拿尺子大概量个初值就行，或者是CAD模型里的设计值

**Comment by Zeqing0213** [comment]
好的好的，感谢，近期在差速机器人上调试的时候发现了一个数据上的问题，机器人执行旋转操作的时候，estimator/odom话题下的Z轴角速度恒定为0，但是轮式编码器的Z就是正常的数据，这个可能是什么问题造成的？

**Comment by Zeqing0213** [comment]
相机、IMU和轮速的外参全部标定好了，然后运行的时候发现Z轴角速度很异常

**Comment by Zeqing0213** [comment]
我们使用的IMU是六轴IMU，但是加速度数据不太准确，但是陀螺仪的数据比较准确，但是最后估计出来的Z轴角速度为啥会是0。这个问题点目前还没有很大的思路。然后还想请教一下，如果IMU只想使用陀螺仪数据，不使用加速度数据，在代码方面应该如何修改呢？非常感谢解惑

**Comment by TouchDeeper** [comment]
@Zeqing0213 
1. 是不是坐标系的问题？沿垂直于地面的角速度不应该为0，其余两个轴确实基本为0
2. IMU的预积分loss中把速度和平移屏蔽掉

**Comment by Zeqing0213** [comment]
好的感谢，我仔细研究一下

**Comment by Zeqing0213** [comment]
> @Zeqing0213
> 
> 1. 是不是坐标系的问题？沿垂直于地面的角速度不应该为0，其余两个轴确实基本为0
> 2. IMU的预积分loss中把速度和平移屏蔽掉

我们单独使用了6轴IMU，没有使用REALSENSE中自带的IMU，我推测应该是相机坐标系和IMU坐标系变换的问题

**Comment by TouchDeeper** [comment]
是的，换了IMU，外参也得改

**Comment by Zeqing0213** [comment]
相机和imu这个坐标系变换问题应该怎么去入手修改呢？

**Comment by TouchDeeper** [comment]
配置文件里的外参参数需要修改

**Comment by Zeqing0213** [comment]
外参这块之前用imu和相机做过联合标定了，修改了外参之后，出现了Z轴角速度恒定为0这个情况。我记得realsense里边imu和相机好像是在一个坐标系里边，如果我用单独的六轴imu和单独的单目相机。在代码中坐标系变换相关部分需要做什么改动吗？

**Comment by TouchDeeper** [comment]
> 外参这块之前用imu和相机做过联合标定了，修改了外参之后，出现了Z轴角速度恒定为0这个情况。我记得realsense里边imu和相机好像是在一个坐标系里边，如果我用单独的六轴imu和单独的单目相机。在代码中坐标系变换相关部分需要做什么改动吗？

支持的，只要把imu和相机的外参在配置文件里修改了就行，代码不用改

**Comment by Zeqing0213** [comment]
好的，感谢。我修改一下config
