### ISSUE TITLE
What is td_wheel?

### ISSUE THREAD

**Issue by awesomesiddhu** [TouchDeeper/VIW-Fusion#33]
Is td_wheel the time offset between IMU and Wheel? Or is it the time offset between Camera and Wheel? 
            curTime = feature.first + td;
            curTime_wheel = curTime - td_wheel;
            
 Is td_wheel calculated as the backward offset from IMU timestamp to wheel timestamp?

**Comment by TouchDeeper** [comment]
td_wheel is the time offset between IMU and Wheel, and curTime_wheel = curTime - td_wheel;
you can refer to [viwo_data_simulation](https://github.com/TouchDeeper/viwo_data_simulation/blob/377e093f5f21a2a886b8b507a37c3f273063fa0f/main/gener_alldata_VIW.cpp#L151) for the usage of td_wheel
