### ISSUE TITLE
关于viw-fusio的使用

### ISSUE THREAD

**Issue by supersupercoconut** [TouchDeeper/VIW-Fusion#34]
感谢您的开源项目！
    我之前使用安装在车上的D435i采集数据来运行vinsrgbd，感觉定位的效果很差。我个人推测是使用vins的时候没有对imu进行充分的激励，导致算法经常提示 no enough feature 以及IMU excitation not enouth。因为我的传感器固连到车上，所以很难拖动或者晃动车辆本身来完成imu的充分激励。不知道使用您开源的算法是否也需要对imu做充分激励。
    并且我现在想了解下关于wheel轮式里程计相关原理，不知道您是否可以推荐一些paper或者blog。

期待您的回复！

**Comment by supersupercoconut** [comment]
我还想询问下关于wheel与imu的标定方法，因为我感觉wheel测量得到的角速度不准，想直接获取到imu的外参，然后直接用imu上测量得到的角速度替换wheel上的数据

**Comment by supersupercoconut** [comment]
我在后续运行程序中使用了您开源的数据集，但是我的运行轨迹中出现了一个z轴高度上的偏差。我不知道这个偏差是否正常。其中path对应的话题为 /viwo/path
![屏幕截图 2024-09-03 210331](https://github.com/user-attachments/assets/da89aba1-c70b-44cf-863f-b9384bdfb335)

**Comment by TouchDeeper** [comment]
> 感谢您的开源项目！ 我之前使用安装在车上的D435i采集数据来运行vinsrgbd，感觉定位的效果很差。我个人推测是使用vins的时候没有对imu进行充分的激励，导致算法经常提示 no enough feature 以及IMU excitation not enouth。因为我的传感器固连到车上，所以很难拖动或者晃动车辆本身来完成imu的充分激励。不知道使用您开源的算法是否也需要对imu做充分激励。 并且我现在想了解下关于wheel轮式里程计相关原理，不知道您是否可以推荐一些paper或者blog。
> 
> 期待您的回复！

回复：在平面移动机器人上使用VIO需要绕8字才能初始化，且初始化精度一般，轮速能够提供初始化的鲁棒性和精度，轮式里程计的原理可以参考仓库里的thesis。



> 我还想询问下关于wheel与imu的标定方法，因为我感觉wheel测量得到的角速度不准，想直接获取到imu的外参，然后直接用imu上测量得到的角速度替换wheel上的数据

回复：wheel和imu的外参通过测量或者CAD设计值给个初值，viw-fusion会在线微调



> 我在后续运行程序中使用了您开源的数据集，但是我的运行轨迹中出现了一个z轴高度上的偏差。我不知道这个偏差是否正常。其中path对应的话题为 /viwo/path ![屏幕截图 2024-09-03 210331](https://private-user-images.githubusercontent.com/137087582/363992838-da89aba1-c70b-44cf-863f-b9384bdfb335.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTY0ODYsIm5iZiI6MTcyNTQxNjE4NiwicGF0aCI6Ii8xMzcwODc1ODIvMzYzOTkyODM4LWRhODlhYmExLWM3MGItNDRjZi04NjNmLWI5Mzg0YmRmYjMzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwMjE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjQwYzUyMTBkYzhmZTA2YThhMzBmNWQ0ZGNlMjJjM2Y3MmNlMjU3NGJiMjhkNzQzY2IzNTZiYzI4MTZjODFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BuNcrOBdjP2SArVaNAzZgiegXbXgYZCSF7Us_eT9YC0)

回复：对于里程计，z轴上肯定会慢慢漂移，累计误差不可避免，加上平面约束只是减慢漂移。要想比较彻底的消除z轴上的漂移，需要回环检测或者在整个轨迹上做优化或者是使用PGO进行优化。

**Comment by supersupercoconut** [comment]
> > 感谢您的开源项目！ 我之前使用安装在车上的D435i采集数据来运行vinsrgbd，感觉定位的效果很差。我个人推测是使用vins的时候没有对imu进行充分的激励，导致算法经常提示 no enough feature 以及IMU excitation not enouth。因为我的传感器固连到车上，所以很难拖动或者晃动车辆本身来完成imu的充分激励。不知道使用您开源的算法是否也需要对imu做充分激励。 并且我现在想了解下关于wheel轮式里程计相关原理，不知道您是否可以推荐一些paper或者blog。
> > 期待您的回复！
> 
> 回复：在平面移动机器人上使用VIO需要绕8字才能初始化，且初始化精度一般，轮速能够提供初始化的鲁棒性和精度，轮式里程计的原理可以参考仓库里的thesis。
> 
> > 我还想询问下关于wheel与imu的标定方法，因为我感觉wheel测量得到的角速度不准，想直接获取到imu的外参，然后直接用imu上测量得到的角速度替换wheel上的数据
> 
> 回复：wheel和imu的外参通过测量或者CAD设计值给个初值，viw-fusion会在线微调
> 
> > 我在后续运行程序中使用了您开源的数据集，但是我的运行轨迹中出现了一个z轴高度上的偏差。我不知道这个偏差是否正常。其中path对应的话题为 /viwo/path ![屏幕截图 2024-09-03 210331](https://private-user-images.githubusercontent.com/137087582/363992838-da89aba1-c70b-44cf-863f-b9384bdfb335.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTY0ODYsIm5iZiI6MTcyNTQxNjE4NiwicGF0aCI6Ii8xMzcwODc1ODIvMzYzOTkyODM4LWRhODlhYmExLWM3MGItNDRjZi04NjNmLWI5Mzg0YmRmYjMzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQwMjE2MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjQwYzUyMTBkYzhmZTA2YThhMzBmNWQ0ZGNlMjJjM2Y3MmNlMjU3NGJiMjhkNzQzY2IzNTZiYzI4MTZjODFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BuNcrOBdjP2SArVaNAzZgiegXbXgYZCSF7Us_eT9YC0)
> 
> 回复：对于里程计，z轴上肯定会慢慢漂移，累计误差不可避免，加上平面约束只是减慢漂移。要想比较彻底的消除z轴上的漂移，需要回环检测或者在整个轨迹上做优化或者是使用PGO进行优化。

感谢您的回复！！！ 我在实际使用您代码的时候发现 (1) wheel的内参估计出的sx sy sz中sx sz都是0.7~0.9左右, 但是对于sy取值是10*8次方  (2)实际使用中的wheel与imu之间的外参估计也并没有在output中进行输出，我还在看源码里面的对应部分，尝试将其输出在output文件中。 (3) 我在使用您代码的过程如下(单目 + wheel +imu): 先使用vins-fusion中的外参估计结果，对同一个数据集运行几次，每一次都将运行出来的imu与camera的外参写入yaml参数中，等运行轨迹不再发散之后，再去使用viw-fusion，想使用相同的方法再迭代wheel与imu的外参。不知道这样的方法能不能有效地估计出各个传感器之间的外参

**Comment by TouchDeeper** [comment]
(1) 代码里应该只有sw，sx，sy。其中sw是角速度的比例因子，sx和sy是速度的比例因子
(2) 应该有个输出外参的代码，[在这](https://github.com/TouchDeeper/VIW-Fusion/blob/37075eb8beeaf93acf15bbc86109deee3777faca/vins_estimator/src/utility/visualization.cpp#L174)
(3) 最初的估计值给的合理应该就行

**Comment by supersupercoconut** [comment]
好的，估计是一些yaml文件设置的错误导致这些printf的提示信息都没有被成功打印出来
（1）sy估计的时候出现了 10*8，是不是因为车辆是阿卡曼模型，侧向运动不够明显导致的
（2）输出外参并没有显示出来，估计也是yaml文件设置有问题
感谢您的回复！！

**Comment by TouchDeeper** [comment]
（1） 是不是和问题2有关，可能是配置文件配错了，比如外参固定了，且外参是错的？

**Comment by supersupercoconut** [comment]
我是运行单目+wheel+imu的版本，实际设置的时候是先测试的单目+imu（realsense D435i）运行正常，加入wheel，定性分析感觉加入wheel的精度与单目imu的精度相比没有提升，反而有些下降。wheel与imu的外参只配置了旋转关系，平移向量使用的是(0,0,0)，viw-fusion yaml中设定的是大致外参，需要算法自己优化

**Comment by TouchDeeper** [comment]
yaml中有开启轮速外参优化吗，
有其他paper测过viw-fusion，精度是比vio高的，可能还是配置问题
