### ISSUE TITLE
VINS fail when the wheel disabled 

### ISSUE THREAD

**Issue by weisongwen** [TouchDeeper/VIW-Fusion#35]
Thanks for sharing such an insightful work. When the wheel is distabled, the VINS seems tend to diverge quickly. Based on the provided dataset, the original VINS-Mono can work well in your dataset. Do you have any ideas on this or we need to set some parameters? 

Thanks,. 
Best,
Weisong,

**Comment by TouchDeeper** [comment]
@weisongwen 
I have developed VIW-Fusion based on Vins-Fusion. You can try whether Vins-Fusion will diverge
