### ISSUE TITLE
轮速计参数

### ISSUE THREAD

**Issue by 2017DEVIL** [TouchDeeper/VIW-Fusion#8]
您好！首先非常感谢您的工作并且进行开源，受益匪浅。我是SLAM小白，关于yaml文件中轮速计的相关参数不太明白，比如：
#plane noise
#mono:0.01 stereo:0.005
roll_n: 0.01
#mono:0.01  stereo:0.005
pitch_n: 0.01
#mono:0.05 stereo:0.025
zpw_n: 0.01

# wheel intrinsic
sx: 1.0
sy: 1.0
sw: 1.0
这些是什么参数，表示的是什么意思？您是通过什么标定方法得到的呢？
您的这个开源程序有对应的参考论文吗？期待您的回复

**Comment by TouchDeeper** [comment]
plane noise是平面约束的噪声，平面约束你可以参考论文vins on wheel。

wheel intrinsic是轮速内参，可以理解为各个方向速度的修正因子。

**Comment by 2017DEVIL** [comment]
轮速内参您是怎么得到的？用的什么标定算法呀？还是依靠经验所得

**Comment by TouchDeeper** [comment]
这里给的是初值，运行时会进行在线标定。

**Comment by 2017DEVIL** [comment]
OK，明白了，谢谢您的回复。还有一个问题，您在写这个工程的时候，参考的文章有哪些呀？想找来一并学习一下。

**Comment by TouchDeeper** [comment]
基础架构是VINS-Mono和VINS-Fusion，后续我会把论文放上来

**Comment by 2017DEVIL** [comment]
> 好的，谢谢！我是今年刚刚进入上海交通大学读研的一名研究生，vio-on-wheel是我的研究方向，不知道是否可以加您的微信或者QQ，进一步沟通一下

**Comment by TouchDeeper** [comment]
可以的，你可以把微信二维码发到我的qq邮箱，610690824@qq.com

**Comment by zhh2005757** [comment]
> 可以的，你可以把微信二维码发到我的qq邮箱，[610690824@qq.com](mailto:610690824@qq.com)

我是中科院的一名研究生 ,研究方向和您的类似, 也希望加您的微信互相交流下, 微信二维码可以也发到您的邮箱吗,非常感谢!

**Comment by ZJJ2022415** [comment]
你好，我研究生 ,研究方向和您的类似, 也希望加您的微信互相交流下, 微信二维码可以也发到您的邮箱吗,非常感谢!

> 可以的，你可以把微信二维码发到我的qq邮箱，[610690824@qq.com](mailto:610690824@qq.com)

你好，我也是一名研究生，方向与您相近，希望可以与您交流下， 微信二维码可以也发到您的邮箱吗,非常感谢!
